# Generated by Django 3.2 on 2024-10-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=40)),
            ],
        ),
    ]
